BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Match] (
    [id] INT NOT NULL IDENTITY(1,1),
    [date] DATETIME2 NOT NULL CONSTRAINT [Match_date_df] DEFAULT CURRENT_TIMESTAMP,
    [teamA] NVARCHAR(1000) NOT NULL,
    [teamB] NVARCHAR(1000) NOT NULL,
    [category] NVARCHAR(1000) NOT NULL,
    [winner] NVARCHAR(1000),
    [textDate] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Match_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
